services:
  cml-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cml-mcp
    restart: unless-stopped
    ports:
      - "9006:9000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs